# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

<% require 'socket' %>
<% hostname_val = Socket.gethostname %>

<% @my_host_flag = hostname_val!="svbalance.cure.com.ph" %>
 #remove later
<% dbname = @my_host_flag ? 'densha_development' : 'densha_production' %>

<% the_env = "#{RAILS_ENV}:" %>
<% puts "database.yml: hostname #{hostname_val} dbname #{dbname} hostflag #{@my_host_flag} env #{the_env}" %>

development:
  adapter: jdbcmysql
  database: <%= dbname %>
  username: <%= @my_host_flag ? 'root' : 'scott' %>  
  password: <%= @my_host_flag ? 'Abby789' : 'scott' %> 
  encoding: utf8
  host: <%= @my_host_flag ? 'localhost' : 'dbmysql.cure.com.ph' %>

production:
  adapter: jdbc
  jndi: java:comp/env/jdbc/process
  driver: com.mysql.jdbc.Driver
#  socket: <%= @my_host_flag ? '/opt/local/var/run/mysql5/mysqld.sock' :  '/var/lib/mysql/mysql.sock' %>
# Warning: The database defined as 'test' will be erased and
# re-generated from your development database when you run 'rake'.
# Do not set this db to the same as development or production.
test:
  adapter: mysql
  database: densha_test
  username: root
  password: Abby789
  host: localhost
  encoding: utf8


#  set environment to manual to manage script/console
# eg: RAILS_ENV=manual; export RAILS_ENV; jruby script/console
manual:
  adapter: jdbcmysql
  database: <%= dbname %>
  username: <%= @my_host_flag ? 'root' : 'scott' %>  
  password: <%= @my_host_flag ? 'Abby789' : 'scott' %> 
  encoding: utf8
  host: <%= @my_host_flag ? 'localhost' : 'dbmysql.cure.com.ph' %>

# test comments
#production:
#  adapter: mysql
#  adapter: jdbcmysql
#  driver: com.mysql.jdbc.Driver


#  encoding: utf8  
#production:
#  adapter: mysql
#  database: densha_production
#  username: densha
#  password: densha
#  host: localhost
#  encoding: utf8